name = "aura-flow-api"
main = "src/index.ts"
compatibility_date = "2023-10-30"
node_compat = true

[env.development]
name = "aura-flow-api-dev"

[env.production]
name = "aura-flow-api-prod"

# Environment variables for development
[vars]
NODE_ENV = "development"

# For production, you would add secrets like:
# wrangler secret put OPENAI_API_KEY
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_ANON_KEY
# wrangler secret put JWT_SECRET
# wrangler secret put JWT_REFRESH_SECRET